import Head from 'next/head'
import React, { useState} from 'react';
import styles from '../styles/Home.module.css'
import FirstPage from '../components/FirstPage';
import Chat from '../components/Chat';

export default function Home() {
  const [showChat, setShowChat] = useState(false)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {showChat?<Chat setShowChat={setShowChat}/>:<FirstPage setShowChat={setShowChat}/>}

    </div>
  )
}

